# Generated by Django 6.0 on 2025-12-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_paymentrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='user',
        ),
    ]
